import React from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { ArrowLeft } from 'lucide-react';

const PrivacyPolicy: React.FC = () => {
  const navigate = useNavigate();

  const handleBack = () => {
    navigate('/');
  };

  return (
    <div 
      className="bg-cover bg-top bg-no-repeat min-h-screen w-full text-white"
      style={{ 
        backgroundImage: "url('/img/page_bg.jpg')",
        fontFamily: "'KrutiDev', sans-serif"
      }}
    >
      {/* Header with Back Button */}
      <header className="p-4">
        <div className="container mx-auto hd_bg rounded-xl">
          <div className="flex justify-between items-center px-4 py-6">
            <div className="flex items-center">
              <button 
                onClick={handleBack}
                className="mr-4 p-2 rounded-full bg-[#610419] text-white hover:bg-[#7a0028] transition-colors"
              >
                <ArrowLeft className="w-5 h-5" />
              </button>
              <h1 className="text-lg font-bold theme_text" style={{fontSize: '20px'}}>Privacy Policy</h1>
            </div>
            {/* <Link to="/" className="rupees_icon"> */}
              <img 
                src="/img/logo.png" 
                alt="Logo" 
                className="max-w-full h-auto"
                style={{width: '100px', height: '22px'}}
              />
            {/* </Link> */}
          </div>
        </div>
      </header>

      {/* Main Content */}
      <main className="p-4">
        <div className="container mx-auto">
          <div className="bg-[#FFFAF4] rounded-xl p-6 md:p-8 shadow-md">
            <div className="text-[#610419] font-eng">
              <h1 className="text-2xl md:text-3xl font-bold mb-6 text-center">Privacy Policy</h1>
              
              <div className="space-y-6 text-sm md:text-base leading-relaxed">
                <p className="text-gray-700">
                  This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
                </p>

                <section>
                  <h2 className="text-xl md:text-2xl font-bold mb-4 theme_text">Interpretation and Definitions</h2>
                  
                  <h3 className="text-lg md:text-xl font-semibold mb-3 theme_text">Interpretation</h3>
                  <p className="text-gray-700 mb-4">
                    The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
                  </p>

                  <h3 className="text-lg md:text-xl font-semibold mb-3 theme_text">Definitions</h3>
                  <p className="text-gray-700 mb-3">For the purposes of this Privacy Policy:</p>
                  
                  <ul className="list-disc pl-6 space-y-2 text-gray-700">
                    <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
                    <li><strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
                    <li><strong>Application</strong> refers to Bhakti Bhav App, the software program provided by the Company.</li>
                    <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to DIGIFISH MEDIA PVT. LTD..</li>
                    <li><strong>Country</strong> refers to: Haryana, India.</li>
                    <li><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
                    <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
                    <li><strong>Service</strong> refers to the Application.</li>
                    <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company.</li>
                    <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</li>
                    <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
                  </ul>
                </section>

                <section>
                  <h2 className="text-xl md:text-2xl font-bold mb-4 theme_text">Collecting and Using Your Personal Data</h2>
                  
                  <h3 className="text-lg md:text-xl font-semibold mb-3 theme_text">Types of Data Collected</h3>
                  
                  <h4 className="text-md md:text-lg font-semibold mb-3 theme_text">Personal Data</h4>
                  <p className="text-gray-700 mb-3">
                    While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
                  </p>
                  <ul className="list-disc pl-6 space-y-1 text-gray-700 mb-4">
                    <li>Email address</li>
                    <li>First name and last name</li>
                    <li>Phone number</li>
                    <li>Address, State, Province, ZIP/Postal code, City</li>
                    <li>Usage Data</li>
                  </ul>

                  <h4 className="text-md md:text-lg font-semibold mb-3 theme_text">Usage Data</h4>
                  <p className="text-gray-700 mb-4">
                    Usage Data is collected automatically when using the Service. Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
                  </p>
                  <p className="text-gray-700 mb-4">
                    When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.
                  </p>

                  <h4 className="text-md md:text-lg font-semibold mb-3 theme_text">Information Collected while Using the Application</h4>
                  <p className="text-gray-700 mb-3">
                    While using Our Application, in order to provide features of Our Application, We may collect, with Your prior permission:
                  </p>
                  <ul className="list-disc pl-6 space-y-1 text-gray-700 mb-4">
                    <li>Information regarding your location</li>
                    <li>Pictures and other information from your Device's camera and photo library</li>
                  </ul>
                  <p className="text-gray-700">
                    We use this information to provide features of Our Service, to improve and customize Our Service. You can enable or disable access to this information at any time, through Your Device settings.
                  </p>
                </section>

                <section>
                  <h2 className="text-xl md:text-2xl font-bold mb-4 theme_text">Use of Your Personal Data</h2>
                  <p className="text-gray-700 mb-3">The Company may use Personal Data for the following purposes:</p>
                  <ul className="list-disc pl-6 space-y-2 text-gray-700">
                    <li><strong>To provide and maintain our Service</strong>, including to monitor the usage of our Service.</li>
                    <li><strong>To manage Your Account</strong>: to manage Your registration as a user of the Service.</li>
                    <li><strong>For the performance of a contract</strong>: the development, compliance and undertaking of the purchase contract.</li>
                    <li><strong>To contact You</strong>: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication.</li>
                    <li><strong>To provide You with news</strong>, special offers and general information about other goods, services and events.</li>
                    <li><strong>To manage Your requests</strong>: To attend and manage Your requests to Us.</li>
                    <li><strong>For business transfers</strong>: We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization.</li>
                    <li><strong>For other purposes</strong>: We may use Your information for other purposes, such as data analysis, identifying usage trends.</li>
                  </ul>
                </section>

                <section>
                  <h2 className="text-xl md:text-2xl font-bold mb-4 theme_text">Retention of Your Personal Data</h2>
                  <p className="text-gray-700 mb-4">
                    The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our legal agreements and policies.
                  </p>
                  <p className="text-gray-700">
                    The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service.
                  </p>
                </section>

                <section>
                  <h2 className="text-xl md:text-2xl font-bold mb-4 theme_text">Transfer of Your Personal Data</h2>
                  <p className="text-gray-700 mb-4">
                    Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.
                  </p>
                  <p className="text-gray-700">
                    The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy.
                  </p>
                </section>

                <section>
                  <h2 className="text-xl md:text-2xl font-bold mb-4 theme_text">Delete Your Personal Data</h2>
                  <p className="text-gray-700 mb-4">
                    You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You. Our Service may give You the ability to delete certain information about You from within the Service.
                  </p>
                  <p className="text-gray-700">
                    Please note, however, that We may need to retain certain information when we have a legal obligation or lawful basis to do so.
                  </p>
                </section>

                <section>
                  <h2 className="text-xl md:text-2xl font-bold mb-4 theme_text">Security of Your Personal Data</h2>
                  <p className="text-gray-700">
                    The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.
                  </p>
                </section>

                <section>
                  <h2 className="text-xl md:text-2xl font-bold mb-4 theme_text">Children's Privacy</h2>
                  <p className="text-gray-700 mb-4">
                    Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us.
                  </p>
                  <p className="text-gray-700">
                    If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent's consent before We collect and use that information.
                  </p>
                </section>

                <section>
                  <h2 className="text-xl md:text-2xl font-bold mb-4 theme_text">Changes to this Privacy Policy</h2>
                  <p className="text-gray-700 mb-4">
                    We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.
                  </p>
                  <p className="text-gray-700">
                    You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
                  </p>
                </section>
              </div>

              {/* Back to Home Button */}
              <div className="mt-8 text-center">
                <button 
                  onClick={handleBack}
                  className="bg-[#610419] text-white px-8 py-3 rounded-[10px] font-eng text-lg hover:bg-[#7a0028] transition-colors flex items-center mx-auto"
                >
                  <ArrowLeft className="w-5 h-5 mr-2" />
                  Back to Home
                </button>
              </div>
            </div>
          </div>
        </div>
      </main>

      {/* Footer */}
      <footer className="mt-6 py-4">
        <div className="container mx-auto flex flex-col md:flex-row justify-between items-center text-2xl px-4">
          <div className="flex flex-col md:flex-row md:space-x-6 theme_text text-center font-eng mb-3 md:mb-0 space-y-2 md:space-y-0">
            <Link to="/termsAndConditions" className="theme-text text-lg text-white hover:underline" style={{ fontFamily: 'Calibri, sans-serif' }}>
              Terms & Conditions
            </Link>
            <Link to="/privacyPolicy" className="theme-text text-lg text-white hover:underline" style={{ fontFamily: 'Calibri, sans-serif' }}>
              Privacy Policy
            </Link>
            <Link to="/aboutUs" className="theme-text text-lg text-white hover:underline" style={{ fontFamily: 'Calibri, sans-serif' }}>
              About us
            </Link>
          </div>
        </div>
      </footer>
    </div>
  );
};

export default PrivacyPolicy;