
export const endPoints = {
    getAllMantras: "all-mantras",
    getMantraById: "mantra",
    generateOtp: "generate-otp",
    verifyOtp: "verify-otp",
    getProfile: "profile",
    updateProfile: "profileUpdate",
    getSubscriptionPlans: "subscriptions",
    getSubscriptionPlansById: "subscriptions",
    makePayment: 'cashfree/create-order',
    createSubscription: 'cashfree/subscription/create',
    verifyPayment: 'cashfree/verify-payment',
    getTransactions: 'Usertranctions',
    downloadWallpaper: 'download',
    pujaKarein: 'puja-kare',
    banner: 'banners',
    wallpaperCategories: 'wallpaper-categories',
    contactUs: "contact-us",
    lang: "lang",
    splashScreen: "analytics/app-install/open",
    featureCategory: 'feature-category',
    featureCategoryContent: "feature-category/content",
    wallpaperDeepLinking: 'wallpaper/wallpaper-deeplinking',
    content: 'feature-category/content',
    jaapMalaCount: "feature-category/content",
    mantras: "all-mantras",
    getSingleMantra: "mantra",
    naamJaap: "all-jaapmala",
    getSingleNaamJaap: 'jaapmala',
    chalisa: "all-chalisas",
    getSingleChalisa: "chalisa",
    aarti:'all-artis',
    getSingleAarti: 'arti',
    todaysThought: 'daythoughts',
    vratKathaList: 'katha-categories',
    vratKathaCategoryList: 'katha-category',
    vratKathaById: 'katha',
    homeData: 'homedata',
}
